export type Character = {
  url: string,
  aliases: string[],
  allegiances: any[],
  books: string[],
  born: string,
  culture: string,
  died: string,
  father: string,
  gender: string,
  mother: string,
  name: string,
  playedBy: string[],
  povBooks: any[],
  spouse: string,
  titles: string[],
  tvSeries: string[],
};